apiVersion: v2
name: authgate
description: A lightweight, production-ready OAuth 2.0 / OpenID Connect Authorization Server with PKCE and Device Flow support
type: application
version: 0.1.1
appVersion: "0.24.0"
keywords:
  - oauth
  - oauth2
  - authorization-server
  - oidc
  - openid-connect
  - pkce
  - device-flow
  - jwt
  - token
  - authentication
  - identity
  - sso
  - api-security
home: https://github.com/go-authgate/authgate
sources:
  - https://github.com/go-authgate/authgate
maintainers:
  - name: AuthGate Team
dependencies:
  - name: postgresql
    version: "18.5.15"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "25.3.9"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
