{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authgate.fullname" . }}
  labels:
    {{- include "authgate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.jwt.privateKeyPem }}
  JWT_PRIVATE_KEY_PEM: {{ .Values.jwt.privateKeyPem | quote }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.defaultAdminPassword }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.defaultAdminPassword | quote }}
  {{- end }}
  {{- if eq .Values.database.driver "postgres" }}
  DATABASE_DSN: {{ include "authgate.postgresDsn" . | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  {{- if .Values.metrics.token }}
  METRICS_TOKEN: {{ .Values.metrics.token | quote }}
  {{- end }}
  {{- if .Values.oauth.github.clientSecret }}
  GITHUB_CLIENT_SECRET: {{ .Values.oauth.github.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.gitea.clientSecret }}
  GITEA_CLIENT_SECRET: {{ .Values.oauth.gitea.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.microsoft.clientSecret }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.oauth.microsoft.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oauth.gitlab.clientSecret }}
  GITLAB_CLIENT_SECRET: {{ .Values.oauth.gitlab.clientSecret | quote }}
  {{- end }}
  {{- if .Values.auth.httpApi.authSecret }}
  HTTP_API_AUTH_SECRET: {{ .Values.auth.httpApi.authSecret | quote }}
  {{- end }}
  {{- if .Values.dynamicClientRegistration.token }}
  DYNAMIC_CLIENT_REGISTRATION_TOKEN: {{ .Values.dynamicClientRegistration.token | quote }}
  {{- end }}
{{- end }}
